name: Shop
main: fr.jules_cesar.Shop.main
version: 1.1
author: Jules_Cesar
depend: [Vault]
commands:
    shop:
        description: Utiliser le plugin d'achat/vente.
permissions:
    shop.modification:
      description: Permet de modifier les shops.
      default: false